#!/bin/bash
#NAME: Rahul Sheth
#EMAIL: rahulssheth@g.ucla.edu
#ID: 304779669



all:
	gcc -o lab3a lab3a.c -Wall -Wextra 
clean: 
	rm -rf lab3a
	rm -rf lab3a-304779669.tar.gz
dist:
	tar -czf lab3a-304779669.tar.gz lab3a.c Makefile README
