#NAME: Rahul Sheth
#EMAIL: rahulssheth@g.ucla.edu
#ID: 304779669





default: 
	g++ lab3b.cpp -o lab3b -Wall -Wextra -static-libstdc++ 
dist:
	tar -czf lab3b-304779669.tar.gz Makefile lab3b.cpp README
clean:
	rm -rf lab3b
	rm -rf lab3b-304779669.tar.gz
